on:
  push:
  pull_request:

jobs:
  lint:
    name: 💅 Javascript Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          path: node_modules/
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: 💅 Linting code
        run: |
          yarn install
          yarn lint
